import 'package:flutter/material.dart';

class CitySearchScreen extends StatefulWidget {
  @override
  _CitySearchScreenState createState() => _CitySearchScreenState();
}

class _CitySearchScreenState extends State<CitySearchScreen> {
  List<String> _selectedCities = [];
  final List<String> _allCities = [
    'Lahore',
    'Islamabad',
    'Karachi',
    'Rawalpindi',
    'Faisalabad',
    'Multan',
    'Gujranwala',
    'Sialkot',
    'Lodhran',
    'Sargodha',
    'Bahawalpur',
    'Sahiwal',
    'Gujrat',
    'Larkana',
    'Kasur',
    'Rahim Yar Khan',
    'Jhang',
    'Sheikhupura',
    'Mirpur Khas',
    'Chiniot',
    'Sukkur',
    'Chakwal',
    'Mardan',
    'Ghotki',
    'Okara',
    'Jacobabad',
    'Wah Cantonment',
    'Dadu',
    'Khuzdar',
    'Muzaffargarh',
    'Khanewal',
    'Hafizabad',
    'Kohat',
    'Bhakkar',
    'Haripur',
    'Malakand',
    'Attock',
    'Batgram',
    'Mandi Bahauddin',
    'Bannu',
    'Jalalpur Jattan',
    'Mianwali',
    'Chaman',
    'Kandhkot',
    'Swabi',
    'Charsadda',
    // Additional cities
    'Abbottabad',
    'Gujranwala',
    'Bahawalnagar',
    'Kasur',
    'Gujrat',
    'Sahiwal',
    'Jhelum',
    'Sadiqabad',
    'Nawabshah',
    'Sanghar',
    'Charsadda',
    'Sukkur',
    'Khairpur',
    'Muzaffarabad',
    'Turbat',
    'Sukkur',
    'Dera Ghazi Khan',
    'Mirpur Khas',
    'Mandi Bahauddin',
    'Jacobabad',
    'Sialkot',
    'Sheikhupura',
    'Bahawalpur',
    'Chiniot',
    'Chaman',
    'Kandhkot',
    'Nawabshah',
    'Khanewal',
    'Dera Ismail Khan',
    'Hafizabad',
    'Kohat',
    'Jaranwala',
    'Kamalia',
    'Jalalpur Jattan',
    'Kotli',
    'Layyah',
    'Kohlu',
    'Karak',
    'Kasur',
    'Khanewal',
    'Larkana',
    'Jhang',
    'Karak',
    'Khuzdar',
    'Chaman',
    'Kandhkot',
    'Swabi',
    'Charsadda',
    // More cities and sub-cities
    'Peshawar',
    'Quetta',
    'Hyderabad',
    'Sukkur',
    'Bahawalpur',
    'Sialkot',
    'Gujrat',
    'Jhelum',
    'Sahiwal',
    'Sheikhupura',
    'Khanewal',
    'Mianwali',
    'Hafizabad',
    'Chiniot',
    'Narowal',
    'Kamoke',
    'Jhang',
    'Sadiqabad',
    'Mandi Bahauddin',
    'Toba Tek Singh',
    'Shakargarh',
    'Khushab',
    'Charsadda',
    'Muzaffargarh',
    'Daska',
    'Gojra',
    'Muridke',
    'Kharian',
    'Pakpattan',
    'Vehari',
    'Burewala',
    'Nowshera',
    'Kandhkot',
    'Murree',
    'Hangu',
    'Kundian',
    'Muzaffarabad',
    'Kot Addu',
    'Hasilpur',
    'Arifwala',
    'Chaman',
    'Pasrur',
    'Zhob',
    'Hala',
    'Shikarpur',
    'Matiari',
    'Ghotki',
    'Naushahro Feroze',
    'New Mirpur City',
    'Kamra',
    'Bannu',
    'Karak',
    'Tando Allahyar',
    'Tando Adam',
    'Usta Muhammad',
    'Qila Abdullah',
    'Dera Murad Jamali',
    'Havelian',
    'Jatoi',
    'Kahuta',
    'Pindi Gheb',
    'Gwadar',
    'Kotli',
    'Loralai',
    'Dera Bugti',
    'Kot Sultan',
    'Shujaabad',
    'Tando Muhammad Khan',
    'Haripur',
    'Shahdadkot',
    'Lakki Marwat',
    'Barkhan',
    'Bhakkar',
    'Jampur',
    'Haroonabad',
    'Sarai Alamgir',
    'Shahkot',
    'Tando Jam',
    'Mailsi',
    'Chunian',
    'Ahmadpur East',
    'Kot Radha Kishan',
    'Timargara',
    'Basti Malook',
    'Khanpur',
    'Wazirabad',
    'Upper Dir',
    'Kabirwala',
    'Shahpur',
    'Moro',
    'Thul',
    'Mingora',
    'Tank',
    'Chak Azam Sahu',
    'Chuhar Kana',
    'Taunsa',
    'Kahror Pakka',
    'Kallar Kahar',
    'Jalalpur Pirwala',
    'Kalabagh',
    'Darya Khan',
    'Badin',
    'Lala Musa',
    'Ratodero',
    'Warburton',
    'Dunyapur',
    'Pir Mahal',
    'Sodhra',
    'Rajanpur',
    'Talagang',
    'Naudero',
    'Kamar Mushani',
    'Shahdadpur',
    'Pind Dadan Khan',
    'Pattoki',
    'Kahna',
    'Chishtian Mandi',
    'Khewra',
    'Kunri',
    'Thatta',
    'Sakrand',
    'Leiah',
    'Tando Muhammad Khan',
    'Lalian',
    'Ranipur',
    'Rohri',
    'Matli',
    'Zahir Pir',
    'Chawinda',
    'Chakwal',
    'Pindi Bhattian',
    'Basirpur',
    'Hujra Shah Muqim',
    'Kunjah',
    'Tandlianwala',
    'Kanganpur',
    'Tando Ghulam Ali',
    'Sarai Naurang',
    'Kalur Kot',
    'Khairpur Nathan Shah',
    'Tandur',
    'Mananwala',
    'Pir Jo Goth',
    'Kandiari',
    'Chor',
    'Jalalpur',
    'Talhar',
    'Bhopalwala',
    'Saddar Gogera',
    'Zaida',
    'Khurrianwala',
    'Paharpur',
    'Usta Muhammad',
    'Ghauspur',
    'Hasan Abdal',
    'Mailsi',
    'Kallur Kot',
    'Akora',
    'Gharo',
    'Ratodero',
    'Chawinda',
    'Surkhpur',
    'Chak Two Hundred Forty-Nine TDA',
    'Mustafabad',
    'Tangi',
    'Lachi',
    'Kot Samaba',
    'Khurianwala',
    'Khewra',
    'Raja Jang',
    'Narang Mandi',
    'Sinjhoro',
    'Mehar',
    'Sehwan',
    'Khangarh',
    'Sarai Sidhu',
    'Chawinda',
    'Pir Sohawa',
    'Akbar',
    'Karor',
    'Dandot',
    'Faruka',
    'Tando Allahyar',
    'Bhag',
    'Khairpur Nathan Shah',
    'Pabbi',
    'Mankera',
    'Goth Radhan',
    'Bhawana',
    'Lakki',
    'Mamu Kanjan',
    'Feroz Watwan',
    'Daur',
    'Dandot RS',
    'Hasilpur',
    'Kharan',
    'Lalian',
    'Noorpur Thal',
    'Chak',
    'Fort Abbas',
    'Liaqatabad',
    'Bela',
    'Jati',
    'Pir Illahi Bakhsh',
    'Kallur Kot',
    'Tandlianwala',
    'Naukot',
    'Fatehpur',
    'Dullewala',
    'Bhag',
    'Goth Machhi',
    'Rojhan',
    'Dhoro Naro',
    'Bhera',
    'Kot Sultan',
    'Sarai Naurang',
    'Lalian',
    'Khewra',
    'Pind Dadan Khan',
    'Dunyapur',
    'Kot Addu',
    'Chak',
    'Fort Abbas',
    'Liaqatabad',
    'Bela',
    'Jati',
    'Pir Illahi Bakhsh',
    'Kallur Kot',
    'Tandlianwala',
    'Naukot',
    'Fatehpur',
    'Dullewala',
    'Bhag',
    'Goth Machhi',
    'Rojhan',
    'Dhoro Naro',
    'Bhera',
    'Kot Sultan',
    'Sarai Naurang',
    'Lalian',
    'Khewra',
    'Pind Dadan Khan',
    'Dunyapur',
    'Kot Addu',
    'Ahmedpur East',
    'Dunga Bunga',
    'Jahanian Shah',
    'Khurrianwala',
    'Kot Mumin',
    'Lakhi',
    'Mian Channun',
    'Moza Shahwala',
    'Pind Dadan Khan',
    'Rohri',
    'Alipur',
    'Basirpur',
    'Burewala',
    'Chak Jhumra',
    'Chak Kamal Khan',
    'Chichawatni',
    'Chiniot',
    'Chishtian Mandi',
    'Choa Saidan Shah',
    'Chunian',
    'Dajal',
    'Darya Khan',
    'Daska',
    'Daud Khel',
    'Daultala',
    'Dera Din Panah',
    'Dhanot',
    'Dullewala',
    'Dunga Bunga',
    'Dunyapur',
    'Faqirwali',
    'Fateh Jang',
    'Fort Abbas',
    'Gojra',
    'Gujar Khan',
    'Gujar Khan',
    'Gujranwala',
    'Gujrat',
    'Harappa',
    'Haveli',
    'Hazro',
    'Hujra Shah Muqim',
    'Jahanian Shah',
    'Jalalpur Jattan',
    'Jalalpur Pirwala',
    'Jalalpur',
    'Jampur',
    'Jand',
    'Jaranwala',
    'Jatoi',
    'Jhawarian',
    'Jhelum',
    'Kahna',
    'Kahror Pakka',
    'Kallar Kahar',
    'Kalur Kot',
    'Kamalia',
    'Kamar Mushani',
    'Kameer',
    'Kamoke',
    'Kamra',
    'Kanganpur',
    'Karor Lal Esan',
    'Kasur',
    'Khairpur Tamiwali',
    'Khairpur',
    'Khanqah Sharif',
    'Kharian',
    'Khewra',
    'Khoski',
    'Khushab',
    'Kot Addu',
    'Kot Mithan',
    'Kot Radha Kishan',
    'Kot Sultan',
    'Kundian',
    'Kunjah',
    'Lahore',
    'Lakki Marwat',
    'Lala Musa',
    'Lalian',
    'Layyah',
    'Liaquat Pur',
    'Lodhran',
    'Malakwal',
    'Malakwal',
    'Mamoori',
    'Mandibahauddin',
    'Mangla',
    'Mandi Bahauddin',
    'Mandra',
    'Mangla',
    'Mankera',
    'Mansehra',
    'Mian Channun',
    'Miani',
    'Mianwali',
    'Mianwali',
    'Minchinabad',
    'Mingora',
    'Mitha Tiwana',
    'Mithi',
    'Mongowali',
    'Moza Shahwala',
    'Multan',
    'Muridke',
    'Murree',
    'Mustafabad',
    'Muzaffargarh',
    'Nankana Sahib',
    'Narang',
    'Narowal',
    'Nasirabad',
    'Naudero',
    'Naushahra Virkan',
    'Nazir Town',
    'Nowshera',
    'Okara',
    'Pakpattan',
    'Pasrur',
    'Pattoki',
    'Phalia',
    'Pind Dadan Khan',
    'Pindi Bhattian',
    'Pindi Gheb',
    'Pir Mahal',
    'Qadirpur Ran',
    'Qasba Gujrat',
    'Qila Didar Singh',
    'Qila Safed',
    'Quaidabad',
    'Rabwah',
    'Rajanpur',
    'Raja Sansi',
    'Rampur',
    'Ranipur',
    'Ratodero',
    'Rawalpindi',
    'Renala Khurd',
    'Robat Thana',
    'Rojhan',
    'Sadiqabad',
    'Sahiwal',
    'Sahiwal',
    'Sakrand',
    'Samaro',
    'Samasatta',
    'Sambrial',
    'Sammundri',
    'Sanghar',
    'Sangla Hill',
    'Sangote',
    'Sanjwal',
    'Sarai Alamgir',
    'Sarai Naurang',
    'Sarai Sidhu',
    'Sarai Sidhu',
    'Sarai Sultan',
    'Sargodha',
    'Shadiwal',
    'Shahdad Kot',
    'Shahdadpur',
    'Shahkot',
    'Shahpur Chakar',
    'Shahpur Saddar',
    'Shahpur',
    'Shahr Sultan',
    'Shakargarh',
    'Sharqpur Sharif',
    'Shehr Sultan',
    'Sheikhupura',
    'Shujaabad',
    'Sialkot',
    'Sillanwali',
    'Sinjhoro',
    'Sita Road',
    'Sobhaga',
    'Sodhra',
    'Sohawa',
    'Suhbatpur',
    'Sujawal',
    'Sukheke Mandi',
    'Sukkur',
    'Surkhpur',
    'Talagang',
    'Talamba',
    'Talhar',
    'Tandlianwala',
    'Tando Adam',
    'Tando Allahyar',
    'Tando Bago',
    'Tando Ghulam Ali',
    'Tando Jam',
    'Tando Muhammad Khan',
    'Tank',
    'Tarbela',
    'Taunsa',
    'Toba Tek Singh',
    'Topi',
    'Tulamba',
    'Ubauro',
    'Uch Sharif',
    'Umarkot',
    'Upper Dir',
    'Usta Muhammad',
    'Vihari',
    'Wah Cantonment',
    'Wazirabad',
    'Yazman Mandi',
    'Zafarwal',
    'Zahir Pir',
    'Zhob',
    'Ziarat',
  ];

  TextEditingController _searchController = TextEditingController();
  bool _selectAll = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('City Search'),
      ),
      body: Column(
        children: [
          Padding(
            padding: const EdgeInsets.all(8.0),
            child: Row(
              children: [
                Expanded(
                  child: TextField(
                    controller: _searchController,
                    decoration: InputDecoration(
                      labelText: 'Search',
                      border: const OutlineInputBorder(),
                      suffixIcon: IconButton(
                        icon: const Icon(Icons.clear),
                        onPressed: () {
                          _searchController.clear();
                          setState(() {});
                        },
                      ),
                    ),
                    onChanged: (value) {
                      setState(() {});
                    },
                  ),
                ),
                Checkbox(
                  value: _selectAll,
                  onChanged: (value) {
                    setState(() {
                      _selectAll = value!;
                      if (value) {
                        _selectedCities = List.from(_allCities);
                      } else {
                        _selectedCities.clear();
                      }
                    });
                  },
                ),
                const Text('All'),
              ],
            ),
          ),
          Expanded(
            child: ListView.builder(
              itemCount: _allCities.length,
              itemBuilder: (context, index) {
                String city = _allCities[index];
                if (_searchController.text.isNotEmpty &&
                    !city
                        .toLowerCase()
                        .contains(_searchController.text.toLowerCase())) {
                  return const SizedBox.shrink();
                }
                return CheckboxListTile(
                  title: Text(city),
                  value: _selectedCities.contains(city),
                  onChanged: (isChecked) {
                    setState(() {
                      if (isChecked == true) {
                        _selectedCities.add(city);
                      } else {
                        _selectedCities.remove(city);
                      }
                    });
                  },
                );
              },
            ),
          ),
          ElevatedButton(
            onPressed: () {
              print('Selected Cities: $_selectedCities');
            },
            child: const Text('Submit'),
          ),
        ],
      ),
    );
  }
}
